### ISSUE TITLE
BLD: packaging: setup.py (PyPI), meta.yaml (conda-forge)

### ISSUE THREAD

**Issue by westurner** [looooo/jupyter_freecad_kernel#2]
Packaging would make this even more useful.

- [ ] setup.py
  - https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/setup.py
- [ ] meta.yaml (for conda-forge)
  - https://conda-forge.org/docs/recipe.html

cookiecutter-pypackage has a full set of default project files templated with jinja2:
```bash
pip install cookiecutter
cookiecutter https://github.com/audreyr/cookiecutter-pypackage
cookiecutter audreyr/cookiecutter-pypackage
```
https://github.com/audreyr/cookiecutter-pypackage
https://pypi.org/project/cookiecutter/

## README
- [ ] Installation instructions
  - https://jupyter.readthedocs.io/en/latest/install-kernel.html
  - https://ipython.readthedocs.io/en/latest/install/kernel_install.html
- [ ] Link to https://www.freecadweb.org/wiki/IPython_notebook_integration
  - [ ] Add a link to https://github.com/looooo/freecad-ipython
- Screenshots
  - Cadquery? http://dcowden.github.io/cadquery/quickstart.html#quickstart

```
conda create -n cadproject freecad notebook pip
source activate cadproject
pip install cadquery    jupyter-freecad-kernel
```
